/**
 * Permission for staff DUNNIO ERP
 * @Public
 */
module.exports = {
    /** for user customer */
    CUSTOMER_LIST: 'CUSTOMER_LIST',
    CUSTOMER_DETAIL: 'CUSTOMER_LIST',
    CUSTOMER_CREATE: 'CUSTOMER_CREATE',
    CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
    CUSTOMER_DELETE: 'CUSTOMER_DELETE',

    /** for group customer */
    CUSTOMER_GROUP_LIST: 'CUSTOMER_GROUP_LIST',
    CUSTOMER_GROUP_DETAIL: 'CUSTOMER_GROUP_LIST',
    CUSTOMER_GROUP_CREATE: 'CUSTOMER_GROUP_CREATE',
    CUSTOMER_GROUP_UPDATE: 'CUSTOMER_GROUP_UPDATE',
    CUSTOMER_GROUP_DELETE: 'CUSTOMER_GROUP_DELETE',

    /** for rank customer */
    RANK_LIST: 'RANK_LIST',
    RANK_DETAIL: 'RANK_LIST',
    RANK_CREATE: 'RANK_CREATE',
    RANK_UPDATE: 'RANK_UPDATE',
    RANK_DELETE: 'RANK_DELETE',

    /** extra: for customer history */
    CUSTOMER_HISTORY: 'CUSTOMER_HISTORY'
};
