import mongoose from 'mongoose';

/**
 * Sub Schema For ItemSchema
 * @public
 */
const designSchema = new mongoose.Schema(
    {
        /** may đo */
        jacket_style_combined: { type: String },
        jacket_lapel_type: { type: String },
        jacket_wide_lapel: { type: String },
        jacket_chest_pocket: { type: String },
        jacket_fit: { type: String },
        jacket_pockets_type: { type: String },
        jacket_sleeve_buttons: { type: String },
        jacket_vent: { type: String },
        jacket_length: { type: String },
        jacket_finishing: { type: String },

        pants_fit: { type: String },
        pants_peg: { type: String },
        pants_belt: { type: String },
        pants_front_pocket: { type: String },
        pants_back_pocket_combine: { type: String },
        pants_cuff: { type: String },
        pants_length: { type: String },
        pants_rise: { type: String },
        pants_belt_loops: { type: String },
        pants_waistband: { type: String },
        pants_back_pocket_style: { type: String },

        waistcoat_piece: { type: String },
        waistcoat_style_combined: { type: String },
        waistcoat_lapel: { type: String },
        waistcoat_lapel_width: { type: String },
        waistcoat_bottom: { type: String },
        waistcoat_chest_pocket: { type: String },
        waistcoat_pockets: { type: String },

        shirt_neck: { type: String },
        shirt_neck_buttons: { type: String },
        shirt_cuffs: { type: String },
        shirt_neck_no_interfacing: { type: String },
        shirt_fit: { type: String },
        shirt_sleeve: { type: String },
        shirt_chest_pocket_type: { type: String },
        shirt_pleats: { type: String },
        shirt_chiet: { type: String },
        shirt_cut: { type: String },
        shirt_sleeve_details: { type: String },
        shirt_chest_pocket: { type: String },
        shirt_epaulettes: { type: String },

        coat_model: { type: String },
        coat_fastening: { type: String },
        coat_lapel_length: { type: String },
        coat_lapel_style: { type: String },
        coat_lapel_wide: { type: String },
        coat_length: { type: String },
        coat_fit: { type: String },
        coat_chest_pocket: { type: String },
        coat_pockets_type: { type: String },
        coat_welted: { type: String },
        coat_belt: { type: String },
        coat_sleeve: { type: String },
        coat_backcut: { type: String },
        coat_epaulettes: { type: String },
        coat_gunflaps: { type: String },
        coat_buttons: { type: String },

        zip_lenght: { type: String },
        zip_cut: { type: String },
        zip_rise: { type: String },
        zip_belt: { type: String },
        zip_belt_loops: { type: String },
        zip_waistband: { type: String },
        zip_front_pocket: { type: String },
        zip_back_pocket: { type: String },
        zip_back_pocket_type: { type: String },

        skirt_lenght: { type: String },
        skirt_rise: { type: String },
        skirt_belt: { type: String },
        skirt_belt_loops: { type: String },
        skirt_waistband: { type: String },

        dress_top_style: { type: String },
        dress_necklines: { type: String },
        dress_sleeves: { type: String },
        dress_bottom_style: { type: String },
        dress_length: { type: String },
        dress_vents: { type: String },
        dress_pockets: { type: String },

        /** bảo hành sửa chữa */
        dinh_cuc_quan: { type: String },
        vat_gau: { type: String },
        cat_ngan_quan: { type: String },
        them_dai_quan: { type: String },
        buc_chi_quan: { type: String },
        thay_moc_quan: { type: String },
        noi_bung: { type: String },
        noi_mong: { type: String },
        bop_bung: { type: String },
        bop_mong: { type: String },
        noi_dui: { type: String },
        noi_day: { type: String },
        bop_dui: { type: String },
        bop_day: { type: String },
        noi_ong: { type: String },
        noi_goi: { type: String },
        bop_ong: { type: String },
        bop_goi: { type: String },
        thay_khoa_quan: { type: String },
        noi_suon_quan: { type: String },
        bop_suon_quan: { type: String },
        chinh_sua_form_quan: { type: String },
        dinh_cuc_ao_somi: { type: String },
        buc_chi_ao_somi: { type: String },
        cat_ngan_tay_ao_somi: { type: String },
        cat_ngan_dai_ao_somi: { type: String },
        noi_suon_tay_ao_somi: { type: String },
        bop_suon_tay_ao_somi: { type: String },
        noi_suon_ao_somi: { type: String },
        bop_suon_ao_somi: { type: String },
        sua_vai_ao: { type: String },
        chinh_sua_form_ao: { type: String },
        dinh_cuc_ao_vest: { type: String },
        buc_chi_ao_vest: { type: String },
        cat_ngan_dai_ao_vest: { type: String },
        tang_chieu_dai_ao_vest: { type: String },
        cat_ngan_tay_ao_vest: { type: String },
        tang_chieu_dai_tay_ao_vest: { type: String },
        noi_suon_tay_ao_vest: { type: String },
        bop_suon_tay_ao_vest: { type: String },
        noi_suon_ao_vest: { type: String },
        bop_suon_ao_vest: { type: String },
        noi_rong_vai: { type: String },
        bop_rong_vai: { type: String },
        tra_lai_tay: { type: String },
        thay_doi_form_ao: { type: String },
        dinh_cuc_quan_price: { type: Number, min: 0 },
        vat_gau_price: { type: Number, min: 0 },
        cat_ngan_quan_price: { type: Number, min: 0 },
        them_dai_quan_price: { type: Number, min: 0 },
        buc_chi_quan_price: { type: Number, min: 0 },
        thay_moc_quan_price: { type: Number, min: 0 },
        noi_bung_price: { type: Number, min: 0 },
        noi_mong_price: { type: Number, min: 0 },
        bop_bung_price: { type: Number, min: 0 },
        bop_mong_price: { type: Number, min: 0 },
        noi_dui_price: { type: Number, min: 0 },
        noi_day_price: { type: Number, min: 0 },
        bop_dui_price: { type: Number, min: 0 },
        bop_day_price: { type: Number, min: 0 },
        noi_ong_price: { type: Number, min: 0 },
        noi_goi_price: { type: Number, min: 0 },
        bop_ong_price: { type: Number, min: 0 },
        bop_goi_price: { type: Number, min: 0 },
        thay_khoa_quan_price: { type: Number, min: 0 },
        noi_suon_quan_price: { type: Number, min: 0 },
        bop_suon_quan_price: { type: Number, min: 0 },
        chinh_sua_form_quan_price: { type: Number, min: 0 },
        dinh_cuc_ao_somi_price: { type: Number, min: 0 },
        buc_chi_ao_somi_price: { type: Number, min: 0 },
        cat_ngan_tay_ao_somi_price: { type: Number, min: 0 },
        cat_ngan_dai_ao_somi_price: { type: Number, min: 0 },
        noi_suon_tay_ao_somi_price: { type: Number, min: 0 },
        bop_suon_tay_ao_somi_price: { type: Number, min: 0 },
        noi_suon_ao_somi_price: { type: Number, min: 0 },
        bop_suon_ao_somi_price: { type: Number, min: 0 },
        sua_vai_ao_price: { type: Number, min: 0 },
        chinh_sua_form_ao_price: { type: Number, min: 0 },
        dinh_cuc_ao_vest_price: { type: Number, min: 0 },
        buc_chi_ao_vest_price: { type: Number, min: 0 },
        cat_ngan_dai_ao_vest_price: { type: Number, min: 0 },
        tang_chieu_dai_ao_vest_price: { type: Number, min: 0 },
        cat_ngan_tay_ao_vest_price: { type: Number, min: 0 },
        tang_chieu_dai_tay_ao_vest_price: { type: Number, min: 0 },
        noi_suon_tay_ao_vest_price: { type: Number, min: 0 },
        bop_suon_tay_ao_vest_price: { type: Number, min: 0 },
        noi_suon_ao_vest_price: { type: Number, min: 0 },
        bop_suon_ao_vest_price: { type: Number, min: 0 },
        noi_rong_vai_price: { type: Number, min: 0 },
        bop_rong_vai_price: { type: Number, min: 0 },
        tra_lai_tay_price: { type: Number, min: 0 },
        thay_doi_form_ao_price: { type: Number, min: 0 },

        /** mở rộng */
        jacket_lapel_satin__contrast: { type: String },
        lining__contrast: { type: String },
        handkerchief__contrast: { type: String },
        metal_buttons__contrast: { type: String },
        neck_lining__contrast: { type: String },
        neck_fabric__contrast: { type: String },
        cuffs_fabric__contrast: { type: String },
        chest_pleats: { type: String },

        jacket_lapel_satin__color: { type: String },
        lining__color: { type: String },
        handkerchief__color: { type: String },
        metal_buttons__color: { type: String },
        neck_lining__color: { type: String },
        initials__color: { type: String },
        neck_fabric__color: { type: String },
        cuffs_fabric__color: { type: String },
        chest_pleats__color: { type: String },

        jacket_lapel_satin__color_price: { type: Number, min: 0 },
        lining__color_price: { type: Number, min: 0 },
        handkerchief__color_price: { type: Number, min: 0 },
        metal_buttons__color_price: { type: Number, min: 0 },
        neck_lining__color_price: { type: Number, min: 0 },
        initials__color_price: { type: Number, min: 0 },
        neck_fabric__color_price: { type: Number, min: 0 },
        cuffs_fabric__color_price: { type: Number, min: 0 },
        chest_pleats__color_price: { type: Number, min: 0 },

        laundry_suits: { type: String },
        quick_tailor_vest: { type: String },
        laundry_vest: { type: String },
        theu_dot_ve_ao: { type: String },
        theu_dot_ve_tui: { type: String },
        quick_tailor_pants: { type: String },
        laundry_pants: { type: String },
        theu_dot_cap_quan: { type: String },
        tailor_pants_layer: { type: String },
        quick_tailor_zip: { type: String },
        quick_tailor_skirt: { type: String },
        quick_tailor_dresses: { type: String },
        quick_tailor_shirt: { type: String },
        laundry_shirt: { type: String },
        theu_dot_co_tay: { type: String },
        theu_dot_co_tay_nep: { type: String },
        quick_tailor_gile: { type: String },
        quick_tailor_cloak: { type: String },

        laundry_suits_price: { type: Number, min: 0 },
        quick_tailor_vest_price: { type: Number, min: 0 },
        laundry_vest_price: { type: Number, min: 0 },
        theu_dot_ve_ao_price: { type: Number, min: 0 },
        theu_dot_ve_tui_price: { type: Number, min: 0 },
        quick_tailor_pants_price: { type: Number, min: 0 },
        laundry_pants_price: { type: Number, min: 0 },
        theu_dot_cap_quan_price: { type: Number, min: 0 },
        tailor_pants_layer_price: { type: Number, min: 0 },
        quick_tailor_zip_price: { type: Number, min: 0 },
        quick_tailor_skirt_price: { type: Number, min: 0 },
        quick_tailor_dresses_price: { type: Number, min: 0 },
        quick_tailor_shirt_price: { type: Number, min: 0 },
        laundry_shirt_price: { type: Number, min: 0 },
        theu_dot_co_tay_price: { type: Number, min: 0 },
        theu_dot_co_tay_nep_price: { type: Number, min: 0 },
        quick_tailor_gile_price: { type: Number, min: 0 },
        quick_tailor_cloak_price: { type: Number, min: 0 },
    },
    {
        _id: false,
        timestamps: false
    }
);

module.exports = designSchema;
